#! /bin/bash

basics=" \
    cpio \
    curl \
    daemontools \
    entr \
    git \
    net-tools \
    openssh-server \
    python \
    tmux \
    vim-gtk"

sudo apt-get update && sudo apt-get install $basics -y
